[package]
name = "invoice-cli"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.102"
clap = { version = "4", features = ["derive"] }
chrono = "0.4.38"
inquire = { version = "0.9.4", features = ["date", "editor"] }
tokio = { version = "1", features = ["rt-multi-thread", "macros"]}
rust_decimal = "1.40.0"
invoice-app = { path = "../invoice-app" }
invoice-storage = { path = "../invoice-storage" }
invoice-core = { path = "../invoice-core" }
