
[package]
name = "invoice-gui"
version = "0.1.0"
edition = "2021"

[lib]
name = "invoice_gui_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[dependencies]
anyhow = "1.0.102"
invoice-app     = { path = "../invoice-app" }
invoice-core    = { path = "../invoice-core" }
invoice-storage = { path = "../invoice-storage" }
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0.149"
tauri = { version = "2.10.3", features = [] }
tauri-build = "2.5.6"
tokio = { version = "1.50.0", features = ["full"] }

[build-dependencies]
tauri-build = { version = "2.5.6", features = [] }
